# Generated by Django 5.1.6 on 2025-08-23 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('input_text', models.TextField()),
                ('category', models.CharField(choices=[('doubt', 'Question & Doubt'), ('image_generation', 'Image Generation'), ('learning_roadmap', 'Learning Roadmap'), ('video_generation', 'Video Generation'), ('deep_research', 'Deep Research'), ('idea_exploration', 'Idea Exploration')], max_length=20)),
                ('response_style', models.CharField(choices=[('concise', 'Concise'), ('detailed', 'Detailed'), ('creative', 'Creative'), ('formal', 'Formal'), ('technical', 'Technical')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('generated_prompt', models.TextField()),
                ('ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
